import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import React from "react";
import { getJsonData } from "@/utils/getJsonData";
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export async function generateMetadata(): Promise<Metadata> {
  const headerList = headers();
  const host = headerList.get("host")!;
  const data = await getJsonData(host);

  return {
    title: `${data.info.name} - ${data.info.title}`,
    description: "Generated by create next app",
  };
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
