import { getBaseUrlByHost } from "@/app/blog/utils";

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface ProfileData {
  rssFeed: string;
  info: Info;
  socials: Socials;
  contacts: Contacts;
  skills: Skills;
  projects: Projects;
  workExperiences: WorkExperience[];
}

export interface Contacts {
  Email: string;
  WhatsApp: string;
  Phone: string;
}

export interface Info {
  name: string;
  title: string;
  headline: string;
  description: string[];
  location: string;
  photo: string;
}

export interface Projects {
  intro: string;
  data: Datum[];
}

export interface Datum {
  name: string;
  description: string;
  githubUrl: string;
  liveUrl: null;
  tags: string[];
}

export interface Skills {
  hard: string[];
  soft: string[];
  devops: string[];
}

export interface Socials {
  linkedin: string;
  facebook: string;
  instagram: string;
  github: string;
}

export interface WorkExperience {}

export const getJsonData = async (host: string): Promise<ProfileData> => {
  const baseUrl = getBaseUrlByHost(host);
  const res = await fetch(
    `${baseUrl.toString()}entries/${baseUrl.hostname}.json`
  );
  const data = await res.json();
  return data;
};
