import { getBaseUrlByHost } from "@/app/blog/utils";

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface ProfileData {
  rssFeed: string;
  info: Info;
  socials: Socials;
  contacts: Contacts;
  skills: Skills;
  projects: Project[];
  workExperiences: WorkExperience[];
}

export interface Contacts {
  email: string;
  whatsapp: string;
  phone: string;
}

export interface Info {
  name: string;
  title: string;
  headline: string;
  description: string;
  location: string;
}

export interface Project {
  name: string;
  description: string;
  url: string;
}

export interface Skills {
  hard: string[];
  soft: string[];
  devops: string[];
}

export interface Socials {
  linkedin: string;
  facebook: string;
  instagram: string;
  github: string;
}

export interface WorkExperience {}

export const getJsonData = async (host: string): Promise<ProfileData> => {
  const baseUrl = getBaseUrlByHost(host);
  const res = await fetch(
    `${baseUrl.toString()}/entries/${baseUrl.hostname}.json`
  );
  const data = await res.json();
  return data;
};
