import { getBaseUrlByHost } from "@/app/blogs/utils";
import axios from "axios";

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
export interface ProfileData {
  info: Info;
  rssFeed: string;
  socials: Socials;
  contacts: Record<string, ContactsInterface>;
  projects: Projects;
  skills: Record<string, string[]>;
  workExperiences: WorkExperience[];
  awards: Award[];
  bio: string;
}

export interface ContactsInterface {
  show: string;
  link: string;
}

export interface Info {
  name: string;
  title: string;
  headline: string;
  description: string[];
  location: string;
  photo: string;
}

export interface Projects {
  intro: string;
  data: Datum[];
}

export interface Datum {
  name: string;
  description: string;
  githubUrl: string;
  liveUrl: string;
  tags: string[];
}

export interface Socials {
  linkedin: string;
  facebook: string;
  instagram: string;
  github: string;
}

export interface WorkExperience {
  companyName: string;
  startDate: string;
  endDate: string;
  title: string;
  description: string[];
  city: string;
}

export interface Award {
  title: string;
  date: string;
  issuedBy: string;
  attachment: null;
}

export const getJsonData = async (
  host: string,
): Promise<ProfileData | null> => {
  const baseUrl = getBaseUrlByHost(host);
  console.log(baseUrl);
  const res = await axios.get(
    `${baseUrl.toString()}entries/${baseUrl.hostname}.json`,
  );
  if (res.status !== 200) {
    return null;
  }
  const data = await res.data;
  return data;
};
