name: Deploy to pages

on:
  release:
  workflow_dispatch:

jobs:
  make-html-files:
    name: Make HTML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: natescherer/markdown-to-html-with-github-style-action@v1
        with:
          path: README.md
          outputpath: out
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # The folder the action should deploy.
