name: Deploy to pages

on:
  release:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  make-html-files-and-deploy:
    name: Make HTML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: NullVoxPopuli/action-setup-pnpm@v2

      - name: Build Docusaurus website
        env:
          HUSKY_SKIP_INSTALL: 1
        run: |
          pnpm install --prod --ignore-scripts
          pnpm run doc:build

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # for cname
          cname: help.next-portfolio.nirjalpaudel.com.np
          # Set custom git config user.name and git config user.email. A commit is always created with the same user.
          commit_message: ${{ github.event.head_commit.message }}
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          
