name: Deploy to pages

on:
  release:
  workflow_dispatch:

jobs:
  make-html-files-and-deploy:
    name: Make HTML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: NullVoxPopuli/action-setup-pnpm@v2

      - name: Build Docusaurus website
        env:
          HUSKY_SKIP_INSTALL: 1
        run: |
          pnpm install --prod
          pnpm run doc:build

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
